version: "3.8"

services:
  worker:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ID: ${API_ID}
      API_HASH: ${API_HASH}
      TOKEN: ${TOKEN}
      OWNER_ID: ${OWNER_ID}
      OWNER_USERNAME: ${OWNER_USERNAME}
      DATABASE_URL: ${DATABASE_URL}
      MONGO_URI: ${MONGO_DB_URI}
